server:
  port: 8081

spring:
  application:
    name: customer-info-service
  config:
    import: "optional:configserver:"

# these configurations are now stored in the config server
# eureka:
#   instance:
#     prefer-ip-address: true
#     leaseRenewalIntervalInSeconds=30:
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka