server:
  port: 8082

spring:
  application:
    name: customer-validation-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka