server:
  port: 8083

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:"

# these configurations are now stored in the config server

#   eureka:
#     instance:
#       prefer-ip-address: true
#       leaseRenewalIntervalInSeconds=30:
#     client:
#       fetch-registry: true
#       register-with-eureka: true
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka/

#  cloud:
#    gateway:
#      routes:
#        - id: route-one
#          uri: lb://customer-service
#          predicates:
#            - Path=/verify/{id}
#          filters:
#            - SetPath=/customers/verify/{id}
#        - id: route-two
#          uri: lb://customer-service
#          predicates:
#            - Path=/customers/verify/{id}


