server:
  port: 8080

spring:
  application:
    name: customer-service
  config:
    import: "optional:configserver:"

management:
  endpoints:
    web:
      exposure:
        include: refresh

#logging:
#  pattern:
#    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"