server:
  port: 8888

spring:
  profiles:
    active: default

  application:
    name: cloud-config

  # Fetch configuration from local file system
  #  cloud:
  #    config:
  #      server:
  #        native:
  #          searchLocations: file:///${user.home}/configrepo

  # Fetch configuration from local git
#  cloud:
#    config:
#      server:
#        git:
#          uri: file:///${user.home}/configrepo

  # Fetch configuration from remote git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/papayankey/configrepo
